version: "3.3"
services:
  frontend:
    build: ./frontend
    ports:
      - 3200:3200
    restart: always

  backend:
    build: ./backend
    ports:
      - 4200:4200
    restart: always

  session:
    image: redis:7.0.4
    ports:
      - 7653:6379
    restart: always

  database:
    image: postgres:14.5
    ports:
      - 7654:5432
    environment:
      - POSTGRES_PASSWORD="local_root"
    volumes:
      - saand:/saand/database      
    restart: always

volumes:
  saand:
