version: "3.3"
services:
  redis:
    image: redis:7.0.4
    ports:
      - 7653:6379
    volumes:
      - /saand/redis:/data

  database:
    image: postgres:14.5
    ports:
      - 7654:5432
    environment:
      - POSTGRES_PASSWORD=local_root
      - POSTGRES_DB=saand
    volumes:
      - /saand/postgres:/var/lib/postgresql/data

  proxy:
    image: nginx:1.23.1
    ports:
      - 80:80
    volumes:
      - ./nginx/local:/etc/nginx/conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  saand:
